/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    'flagship-projects': FlagshipProject;
    events: Event;
    blogs: Blog;
    avenues: Avenue;
    members: Member;
    'board-years': BoardYear;
    'legacy-photos': LegacyPhoto;
    faqs: Faq;
    media: Media;
    'contact-submissions': ContactSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'flagship-projects': FlagshipProjectsSelect<false> | FlagshipProjectsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    avenues: AvenuesSelect<false> | AvenuesSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'board-years': BoardYearsSelect<false> | BoardYearsSelect<true>;
    'legacy-photos': LegacyPhotosSelect<false> | LegacyPhotosSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'home-intro': HomeIntro;
    'site-settings': SiteSetting;
    'admin-contact-email': AdminContactEmail;
    'user-contact-email': UserContactEmail;
  };
  globalsSelect: {
    'home-intro': HomeIntroSelect<false> | HomeIntroSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'admin-contact-email': AdminContactEmailSelect<false> | AdminContactEmailSelect<true>;
    'user-contact-email': UserContactEmailSelect<false> | UserContactEmailSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every project card on the projects page and the counts on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  avenue: 'Club Service' | 'Community Service' | 'Professional Service' | 'International Service' | 'District Priority';
  description: string;
  image: string | Media;
  /**
   * Month and year this happened. Powers the year/month filters on the projects page — club years run July to June, so a project dated any month from July through December belongs to that calendar year's edition, and January through June belongs to the following one.
   */
  date: string;
  /**
   * Optional. The blog post telling this project's story — a project card on the home page opens it. Without one the card falls back to the blog index.
   */
  relatedPost?: (string | null) | Blog;
  /**
   * The home page shows up to seven projects. Tick this to put one there; if fewer than seven are ticked, the newest projects fill the rest.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first within the avenue.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every photo and PDF used on the site. Upload here, then pick the file from any page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * What the image shows. Read aloud by screen readers and shown if the image fails to load.
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Write-ups for the blog. The hero image and card summary are what show in the list; everything else appears once a reader opens the post.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string;
  name: string;
  /**
   * The web address for this entry. Leave blank and it is built from the name.
   */
  slug?: string | null;
  /**
   * The image on the blog card and at the top of the post.
   */
  heroImage: string | Media;
  /**
   * One or two sentences. This is all a reader sees on the card before clicking through.
   */
  cardSummary: string;
  /**
   * The post itself — headings, links and formatting all work here.
   */
  details: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Up to three photographs, shown as a gallery at the end of the post.
   */
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Which avenue this post belongs to. It surfaces on that avenue's card in the home page deck.
   */
  avenue: string | Avenue;
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * The five avenues of service. These are the cards in the home page deck and the tags on blog posts — the set rarely changes, but the words and photography here are yours to edit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avenues".
 */
export interface Avenue {
  id: string;
  /**
   * e.g. Community Service.
   */
  name: string;
  /**
   * The web address for this entry. Leave blank and it is built from the name.
   */
  slug?: string | null;
  /**
   * The line that appears on the back of the card when it is turned over.
   */
  description: string;
  /**
   * The photograph on the face of the card.
   */
  image: string | Media;
  /**
   * The marker colour for this avenue. Drawn from the site palette.
   */
  accentColor: 'starlight' | 'cranberry' | 'comet' | 'nebula';
  /**
   * Order in the deck — lower numbers sit on top (0, 1, 2 …).
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * The spotlight tabs in the “Built to break barriers” section of the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flagship-projects".
 */
export interface FlagshipProject {
  id: string;
  title: string;
  /**
   * Short label, e.g. "Flagship since 2019".
   */
  tag: string;
  description: string;
  /**
   * Headline stat, e.g. "60+ players · 14 states".
   */
  stat: string;
  image: string | Media;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everything on the events page. Upcoming events lead the page; past ones fall into the archive below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  name: string;
  /**
   * The web address for this entry. Leave blank and it is built from the name.
   */
  slug?: string | null;
  /**
   * The full write-up shown on the event's own page.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The lead photograph — used on the event card and at the top of its page.
   */
  heroImage: string | Media;
  /**
   * Photographs from the event, shown as a gallery on its page.
   */
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  date: string;
  /**
   * Where it happens — venue, or city.
   */
  location: string;
  /**
   * Controls where the event appears on the page.
   */
  status: 'upcoming' | 'ongoing' | 'past';
  /**
   * Optional. A registration or RSVP link — the button only appears when this is filled in.
   */
  registrationLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The team shown on the Team page and the home page teaser. Add, edit or delete a member here — Priority controls the order they appear in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: string;
  name: string;
  /**
   * Job title / position — e.g. President, Secretary, Member.
   */
  role: string;
  /**
   * Board members show name + designation on the Team page. General members show in the name-only circle grid further down.
   */
  memberType: 'board' | 'general';
  /**
   * A sentence or two shown on the board card — who they are and what they bring. Board members without one simply show their name and designation.
   */
  bio?: string | null;
  photo: string | Media;
  /**
   * The year this board served, entered as the starting year — a term running July 2025 to June 2026 is 2025. Drives the year tabs on the home page.
   */
  year: number;
  /**
   * Display order on the website — lower numbers appear first (0, 1, 2 …).
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * The group photograph for each board. The year tabs on the home page are built from these, and each one pairs with the members carrying the same year.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-years".
 */
export interface BoardYear {
  id: string;
  /**
   * The starting year of the term — a board serving July 2026 to June 2027 is 2026. Must match the year set on that board's members.
   */
  year: number;
  /**
   * The whole board in one photograph. A wide, landscape shot works best.
   */
  groupPhoto: string | Media;
  /**
   * Optional line under the photograph — e.g. the installation venue.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The archive gallery on the Legacy page — hosted on Cloudinary.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legacy-photos".
 */
export interface LegacyPhoto {
  id: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * The questions answered at the bottom of the home page. Keep the answers short — one short paragraph reads best in the accordion.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: string;
  /**
   * Lower numbers appear first (0, 1, 2 …).
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages sent through the contact form on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  /**
   * For your own triage — not shown to the sender.
   */
  status?: ('new' | 'replied' | 'archived') | null;
  /**
   * Whether the notification and acknowledgement actually sent.
   */
  delivery?: {
    adminEmailSent?: boolean | null;
    userEmailSent?: boolean | null;
    /**
     * Set when Resend rejected the send.
     */
    error?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can sign in and edit the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'flagship-projects';
        value: string | FlagshipProject;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'blogs';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'avenues';
        value: string | Avenue;
      } | null)
    | ({
        relationTo: 'members';
        value: string | Member;
      } | null)
    | ({
        relationTo: 'board-years';
        value: string | BoardYear;
      } | null)
    | ({
        relationTo: 'legacy-photos';
        value: string | LegacyPhoto;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  avenue?: T;
  description?: T;
  image?: T;
  date?: T;
  relatedPost?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flagship-projects_select".
 */
export interface FlagshipProjectsSelect<T extends boolean = true> {
  title?: T;
  tag?: T;
  description?: T;
  stat?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  date?: T;
  location?: T;
  status?: T;
  registrationLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  cardSummary?: T;
  details?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  avenue?: T;
  date?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avenues_select".
 */
export interface AvenuesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  accentColor?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  memberType?: T;
  bio?: T;
  photo?: T;
  year?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-years_select".
 */
export interface BoardYearsSelect<T extends boolean = true> {
  year?: T;
  groupPhoto?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legacy-photos_select".
 */
export interface LegacyPhotosSelect<T extends boolean = true> {
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  delivery?:
    | T
    | {
        adminEmailSent?: T;
        userEmailSent?: T;
        error?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The opening sequence on the home page, and the headline it reveals. Shown once per visit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-intro".
 */
export interface HomeIntro {
  id: string;
  /**
   * Turn this off to send visitors straight to the home page.
   */
  enabled?: boolean | null;
  /**
   * The line the home page opens with once the curtain lifts.
   */
  headline: string;
  /**
   * The mark the panels close onto. Leave empty to use the club logo already in the header.
   */
  logo?: (string | null) | Media;
  /**
   * Photographs that slide past on the panels — five or more looks best. Fewer than two skips the intro.
   */
  panelImages?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer links, socials, contact details and copyright. Anything left blank falls back to what the site already ships with.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  /**
   * The 'get involved' column. Leave empty to keep the links the site ships with.
   */
  footerLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Supports {year} and {name} — e.g. “© {year} {name}. All rights reserved.”
   */
  copyrightText?: string | null;
  /**
   * Shown in the footer and on the contact page.
   */
  socialLinks?:
    | {
        platform: 'Instagram' | 'Facebook' | 'LinkedIn' | 'X' | 'YouTube' | 'WhatsApp';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * What lands in the club inbox when somebody uses the contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-contact-email".
 */
export interface AdminContactEmail {
  id: string;
  /**
   * Subject line. You can use {name}, {email}, {phone}, {message} and {date} — they are replaced with the sender's details.
   */
  subject: string;
  /**
   * Optional banner across the top of the email. Wide and short works best.
   */
  headerImage?: (string | null) | Media;
  /**
   * The body of the email. You can use {name}, {email}, {phone}, {message} and {date} — they are replaced with the sender's details.
   */
  richTextBody: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Small print under the message — e.g. why they are receiving this.
   */
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The confirmation the sender receives after using the contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-contact-email".
 */
export interface UserContactEmail {
  id: string;
  /**
   * Subject line. You can use {name}, {email}, {phone}, {message} and {date} — they are replaced with the sender's details.
   */
  subject: string;
  /**
   * Optional banner across the top of the email. Wide and short works best.
   */
  headerImage?: (string | null) | Media;
  /**
   * The body of the email. You can use {name}, {email}, {phone}, {message} and {date} — they are replaced with the sender's details.
   */
  richTextBody: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Small print under the message — e.g. why they are receiving this.
   */
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-intro_select".
 */
export interface HomeIntroSelect<T extends boolean = true> {
  enabled?: T;
  headline?: T;
  logo?: T;
  panelImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  address?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-contact-email_select".
 */
export interface AdminContactEmailSelect<T extends boolean = true> {
  subject?: T;
  headerImage?: T;
  richTextBody?: T;
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-contact-email_select".
 */
export interface UserContactEmailSelect<T extends boolean = true> {
  subject?: T;
  headerImage?: T;
  richTextBody?: T;
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}